services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:?check .env.dist}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    ports:
      - "${WORDPRESS_PORT:?check .env.dist}:80"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE:?check .env.dist}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD:?check .env.dist}
      WORDPRESS_DB_USER: ${MARIADB_USER:?check .env.dist}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        $$_SERVER['HTTPS'] = 'on';
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION:?check .env.dist}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:?check .env.dist}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:?check .env.dist}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER:?check .env.dist}
      PMA_PASSWORD: ${MARIADB_PASSWORD:?check .env.dist}
    depends_on:
      - db

volumes:
  wordpress:
  data:
